import Home from './Home'
import Products from './Products'
import Strategy from './Strategy'
import Careers from './About/Careers'
import Leadership from './About/Leadership'
import Board from './About/Board'
import Investors from './About/Investors'
import Newsroom from './Resource/Newsroom'
import PressReleases from './Resource/PressReleases'
import MediaKit from './Resource/MediaKit'
import Release from './Resource/Release'
import Support from './Resource/Support'
import Contact from './Contact'
export {Home,Products,Strategy,Careers,Leadership,Board,Investors,Newsroom,PressReleases,MediaKit,Release,Support,Contact}
